- pkg: '@webundsoehne-private/nx-nest'
  registry: 'https://verdaccio.dev.webundsoehne.com'
  description: 'A boilerplate to generate Nest.js applications from scratch.'
  schematics:
    - name: app
      description: Creates or edits a application.
    - name: component
      description: Generates default components depending on your application type.
    - name: microservice-provider
      description: Generate the microservice provider library.

- pkg: '@webundsoehne-private/nx-workspace'
  registry: 'https://verdaccio.dev.webundsoehne.com'
  description: 'General purpose workspace schematic extended from the default.'
  schematics:
    - name: move
      description: Move an application or library to another folder.
      forceArguments: true
    - name: remove
      description: Remove an application or library.
      forceArguments: true
    - name: library
      description: Create a library.
      forceArguments: true

