- pkg: '@webundsoehne-private/nx-nest'
  registry: 'https://verdaccio.webundsoehne.com'
  description: 'A boilerplate to generate Nest.js applications from scratch.'
  schematics:
    - name: app
      description: Creates or edits a application.
    - name: component
      description: Generates default components depending on your application type.
    - name: microservice-provider
      description: Generate the microservice provider library.
    - name: backend-interfaces
      description: Generate a common library for database interfaces.
    - name: generator
      description: Creates a single component from the given template.

- pkg: '@webundsoehne-private/nx-workspace'
  registry: 'https://verdaccio.webundsoehne.com'
  description: 'General purpose workspace schematic extended from the default.'
  schematics:
    - name: move
      description: Move an application or library to another folder.
      forceArguments: true
    - name: remove
      description: Remove an application or library.
      forceArguments: true
    - name: library
      description: Create a library.
      forceArguments: true

- pkg: '@webundsoehne/nx-tools'
  description: 'Some generic tools for nx.'
  schematics:
    - name: exports
      description: export a glob pattern from the defined file. an easy index.ts creation.
