stages:
  - install
  - build
  - docs
  - publish
  - sync

cache:
  paths:
    - node_modules/
    - packages/*/node_modules

variables:
  NODE_VERSION: 18-alpine
  PACKAGE_MANAGER: yarn

include:
  - project: bdsm/gitlab-pipes
    file: /templates/node.gitlab-ci.yml
  - project: bdsm/gitlab-pipes
    file: /templates/semantic-release.gitlab-ci.yml

docs:
  stage: docs
  script:
    - yarn docs
  artifacts:
    paths:
      - packages/*/README.md
      - packages/*/docs
  only:
    - master
    - next
    - next-major
    - beta
    - rc
    - alpha
  tags:
    - node

publish:
  variables:
    NPM_LOGIN: $NPM_LOGIN
    RUN_MULTI: 'true'
