image: node:16-alpine

stages:
  - install
  - build
  - docs
  - publish
  - sync

cache:
  paths:
    - node_modules/
    - packages/*/node_modules

install:
  stage: install
  script:
    - yarn --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
      - packages/*/node_modules
    expire_in: 30 minutes
  tags:
    - node

lint:
  stage: build
  script:
    - yarn lint:check
  tags:
    - node

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist/
      - packages/*/dist
  tags:
    - node

docs:
  stage: docs
  script:
    - yarn docs
  artifacts:
    paths:
      - packages/*/README.md
      - packages/*/docs
  only:
    - master
    - next
    - next-major
    - beta
    - rc
    - alpha
  tags:
    - node

publish:
  stage: publish
  image: cenk1cenk2/pipe-semantic-release:latest
  variables:
    GIT_AUTHOR_NAME: semantic-release [bot]
    GIT_AUTHOR_EMAIL: $BANDAID_API_USER_EMAIL
    GIT_COMMITTER_NAME: semantic-release [bot]
    GIT_COMMITTER_EMAIL: $BANDAID_API_USER_EMAIL
    NPM_LOGIN: $NPM_LOGIN
    RUN_MULTI: 'true'
  script:
    - pipe
  only:
    - master
    - next
    - next-major
    - beta
    - rc
    - alpha
  tags:
    - docker

# due to gitlab sync not working on the host
sync:
  stage: sync
  image: bitnami/git:latest
  before_script:
    - git config --global user.name "backend"
    - git config --global user.email "$NPM_WS_EMAIL"
    - mkdir -p ~/.ssh/
    - echo "$GITHUB_DEPLOY_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
    - git remote remove github || true
    - git remote add github git@github.com:tailoredmedia/backend-nx-skeleton.git
    - git checkout $CI_COMMIT_BRANCH
    - git pull origin $CI_COMMIT_BRANCH
    - git pull github $CI_COMMIT_BRANCH
    - git status
    - git push -u github $CI_COMMIT_BRANCH
  only:
    - master
  tags:
    - docker
