image: node:14-alpine

variables:
  PACKAGE_SCOPE: '--scope "@webundsoehne/nx-tools" --scope "@webundsoehne/nx-builders" --scope "@webundsoehne/eslint-config"'

stages:
  - install
  - lint
  - build
  - publish

cache:
  paths:
    - node_modules/
    - packages/*/node_modules

install:
  stage: install
  script:
    - yarn --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
      - packages/*/node_modules
    expire_in: 30 minutes
  tags:
    - node

lint:
  stage: lint
  script:
    - eval yarn command --parallel ${PACKAGE_SCOPE} lint:check
  tags:
    - node

build:
  stage: build
  script:
    - eval yarn command ${PACKAGE_SCOPE} --include-dependencies build
  artifacts:
    paths:
      - packages/*/dist
    expire_in: 30 minutes
  only:
    - develop
    - master
  tags:
    - node

publish:
  stage: publish
  image: cenk1cenk2/drone-semantic-release
  variables:
    PLUGIN_GIT_METHOD: gl
    PLUGIN_MODE: publish
    PLUGIN_ADD_MODULES: semantic-release-monorepo @semantic-release/gitlab
    PLUGIN_OVERRIDE: npx --no-install lerna exec ${PACKAGE_SCOPE} --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo
    PLUGIN_GIT_USER_EMAIL: $BANDAID_API_USER_EMAIL
    PLUGIN_GITLAB_TOKEN: $BANDAID_API_TOKEN_WRITE
    PLUGIN_UPDATE_README_TOC: 'true'
    PLUGIN_README_LOCATION: "README.md $$(find packages -maxdepth 2 -name README.md | paste -sd ' ')"
    PLUGIN_NPM_TOKEN: $NPM_WS_TOKEN
    DRONE_REPO_BRANCH: $CI_COMMIT_REF_NAME
  before_script:
    - apk add --no-cache --no-progress rsync
    - rsync -a $CI_PROJECT_DIR/ /drone/src/
    - cd /drone/src
  script:
    - /semantic-release/release.sh
  after_script:
    - rsync -a /drone/src/ $CI_PROJECT_DIR/
  only:
    - master
  tags:
    - node
