image: node:14-alpine

stages:
  - install
  - lint
  - build
  - docs
  - publish

cache:
  paths:
    - node_modules/
    - packages/*/node_modules

install:
  stage: install
  script:
    - yarn --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
      - packages/*/node_modules
    expire_in: 30 minutes
  tags:
    - node

lint:
  stage: lint
  script:
    - yarn command --parallel lint:check
  tags:
    - node

build:
  stage: build
  script:
    - yarn command build --concurrency 1 --include-dependencies
  artifacts:
    paths:
    - dist/
    - packages/*/dist
  tags:
   - node

docs:
  stage: docs
  script:
    - yarn command docs:readme
    - yarn command docs:jsdoc
    - yarn command docs:toc
    - yarn docs:toc
  artifacts:
    paths:
    - packages/*/README.md
    - packages/*/API.md
  tags:
   - node

publish:
  stage: publish
  image: cenk1cenk2/drone-semantic-release
  variables:
    PLUGIN_GIT_METHOD: gl
    PLUGIN_MODE: release
    PLUGIN_ADD_MODULES: "@qiwi/multi-semantic-release @semantic-release/gitlab"
    PLUGIN_OVERRIDE: multi-semantic-release --sequential-init
    PLUGIN_GIT_USER_EMAIL: $BANDAID_API_USER_EMAIL
    PLUGIN_GITLAB_TOKEN: $BANDAID_API_TOKEN_WRITE
    PLUGIN_UPDATE_README_TOC: "false"
    PLUGIN_NPM_USERNAME: $NPM_WS_USERNAME
    PLUGIN_NPM_PASSWORD: $NPM_WS_PASSWORD
    PLUGIN_NPM_EMAIL: $NPM_WS_EMAIL
    # npm_config_loglevel: verbose
    # PLUGIN_NPM_TOKEN: $NPM_WS_TOKEN
    DRONE_REPO_BRANCH: $CI_COMMIT_REF_NAME
  before_script:
    - apk add --no-cache --no-progress rsync
    - rsync -a $CI_PROJECT_DIR/ /drone/src/
    - cd /drone/src
  script:
    - /semantic-release/release.sh
  after_script:
    - rsync -a /drone/src/ $CI_PROJECT_DIR/
  only:
    - master
    - beta
    - rc
    - alpha
  tags:
    - node
