image: node:14-alpine

variables:
  PACKAGE_SCOPE: '--scope "@webundsoehne/nx-tools" --scope "@webundsoehne/nx-builders"'

stages:
  - install
  - lint
  - build
  - publish

cache:
  paths:
    - node_modules/
    - packages/*/node_modules

install:
  stage: install
  script:
    - yarn --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
      - packages/*/node_modules
    expire_in: 30 minutes
  tags:
    - node

lint:
  stage: lint
  script:
    - eval yarn command --parallel ${PACKAGE_SCOPE} lint:check
  tags:
    - node

build:
  stage: build
  script:
    - eval yarn command ${PACKAGE_SCOPE} --include-dependencies build
  artifacts:
    paths:
      - packages/*/dist
    expire_in: 30 minutes
  only:
    - develop
    - master
  tags:
    - node

publish:
  stage: publish
  image: cenk1cenk2/drone-semantic-release
  variables:
    PLUGIN_GIT_METHOD: gl
    PLUGIN_MODE: predict
    PLUGIN_ADD_MODULES: semantic-release-monorepo @semantic-release/gitlab
    PLUGIN_OVERRIDE: npx --no-install lerna exec ${PACKAGE_SCOPE} --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo
    PLUGIN_GIT_USER_EMAIL: $BANDAID_API_USER_EMAIL
    PLUGIN_GITLAB_TOKEN: $BANDAID_API_TOKEN_WRITE
    NPM_USERNAME: $NPM_WS_USERNAME
    NPM_PASSWORD: $NPM_WS_PASSWORD
    NPM_EMAIL: $NPM_WS_EMAIL
  before_script:
    - apk add --no-cache --no-progress rsync
    - rsync -a $CI_PROJECT_DIR/ /drone/src/
    - cd /drone/src
  script:
    - /semantic-release/release.sh
  after_script:
    - rsync -a /drone/src/ $CI_PROJECT_DIR/
  only:
    - master
  tags:
    - node
