---
version: '3.7'
services:
  monorepo:
    image: cenk1cenk2/node-fnm:latest
    environment:
      SYNC_WAIT: 7
      PROXY_PACKAGES_FOLDER: packages/
      LOG_LEVEL: trace
      SERVICE_0_CWD: packages/ts-utility-types
      SERVICE_0_NAME: ts-utility-types
      SERVICE_0_SYNC: 'true'
      SERVICE_1_CWD: packages/deep-merge
      SERVICE_1_NAME: deep-merge
      SERVICE_1_SYNC: 'true'
      SERVICE_2_CWD: packages/nx-tools
      SERVICE_2_NAME: nx-tools
      SERVICE_2_SYNC: 'true'
      SERVICE_3_CWD: packages/nx-builders
      SERVICE_3_NAME: nx-builders
      SERVICE_3_SYNC: 'true'
      SERVICE_4_CWD: packages/brownie
      SERVICE_4_NAME: brownie
      SERVICE_5_CWD: packages/nestjs-util
      SERVICE_5_NAME: nestjs-util
      SERVICE_5_SYNC: 'true'
      SERVICE_6_CWD: packages/nx-nest
      SERVICE_6_NAME: nx-nest
      SERVICE_7_CWD: packages/patch-package
      SERVICE_7_NAME: patch-package
      SERVICE_8_CWD: packages/nestjs-graphql-typeorm-dataloader
      SERVICE_8_NAME: nestjs-graphql-typeorm-dataloader
      SERVICE_9_CWD: packages/nx-workspace
      SERVICE_9_NAME: nx-workspace
      SERVICE_10_CWD: packages/nestjs-keycloak
      SERVICE_10_NAME: nestjs-keycloak
      SERVICE_10_SYNC: 'true'
      SERVICE_11_CWD: packages/nestjs-keycloak-seeder
      SERVICE_11_NAME: nestjs-keycloak-seeder
      SERVICE_12_CWD: packages/nestjs-util-graphql
      SERVICE_12_NAME: nestjs-util-graphql
      SERVICE_13_CWD: packages/nestjs-util-microservices
      SERVICE_13_NAME: nestjs-util-microservices
      SERVICE_14_CWD: packages/nestjs-util-restful
      SERVICE_14_NAME: nestjs-util-restful
      SERVICE_15_CWD: packages/nestjs-seeder
      SERVICE_15_NAME: nestjs-seeder
    volumes:
      - .:/data
