cli: 'brownie'
loglevel: module
logcolor: true
configDir: '.config/brownie'
localConfig: '.brownie.local.lock'
lock: '.brownie.lock'

workspace:
  requiredDependencies:
    - '@nrwl/cli'
    - '@nrwl/tao'
    - '@nrwl/workspace'
    - '@angular/cli'

package_manager: npm
