---
variables:
  NODE_VERSION: 18-alpine
  # environment variable files that needs to be injected for the frontend build
  NODE_BUILD_ENVIRONMENT_FILES: ''

.docker-common:
  stage: docker
  trigger:
    include:
      - project: bdsm/gitlab-pipes
        file: /templates/docker-build-with-artifacts.gitlab-ci.yml
        ref: main
    strategy: depend

stages:
  - install
  - build
  - docker

include:
  - project: bdsm/gitlab-pipes
    file: /templates/node-nx.gitlab-ci.yml
    ref: main
#
####################################################################
## add your applications here, that should be build as containers ##
####################################################################
# docker-app:
#   extends: .docker-common
#   variables:
#     DOCKERFILE_CONTEXT: ./dist/apps/app
#     DOCKER_IMAGE_NAME: app
#   only:
#     changes:
#       - .gitlab-ci.yml
#       - 'libs/**/*'
#       - 'apps/app/**/*'
#     refs:
#       - master
#       - tags
